### ISSUE TITLE
你好，我有一些问题想请教你一下

### ISSUE THREAD

**Issue by lxy51** [Cassieyy/MultiResUnet3D#1]
你好，我来自山东大学，首先十分感谢你提供的代码。
我有一点疑惑的地方，代码中class MultiResUNet(nn.Module):部分的    def forward(self, x):里面，有这样一行代码：        self.res_path1(x1)，他是否应该改为       x = self.res_path1(x1)。
由于我是这方面的新手，所以很多地方不太懂。

**Comment by Cassieyy** [comment]
> 你好，我来自山东大学，首先十分感谢你提供的代码。 我有一点疑惑的地方，代码中class MultiResUNet(nn.Module):部分的 def forward(self, x):里面，有这样一行代码： self.res_path1(x1)，他是否应该改为 x = self.res_path1(x1)。 由于我是这方面的新手，所以很多地方不太懂。

看到self.res_path1对应类的forward()实际上没有返回值，所以x = self.res_path1(x1)这样写其实也没用，可能self.res_path1这一步是我调试过程中写的，试试把它注释掉，我猜应该没影响。

**Comment by lxy51** [comment]
首先，十分感谢你愿意分享你的代码。
我觉得需要给def forward(self, x):加上返回值，要不然怎么进行跳跃连接，你认为呢？
不知我是否可以加一下您的联系方式，由于我是这个领域的新手，所以有些地方不太懂，我对这个项目很感兴趣，不知道能否等你有时间时咨询你一点东西？

**Comment by Cassieyy** [comment]
> 首先，十分感谢你愿意分享你的代码。 我觉得需要给def forward(self, x):加上返回值，要不然怎么进行跳跃连接，你认为呢？ 不知我是否可以加一下您的联系方式，由于我是这个领域的新手，所以有些地方不太懂，我对这个项目很感兴趣，不知道能否等你有时间时咨询你一点东西？

如果你认为是正确的，那就加上。这个repo是我很久之前create的，细节已经记不清了。

**Comment by lxy51** [comment]
好的，谢谢你的回答

**Comment by lxy51** [comment]
您好，我还有一个问题想请教您，您当初拿这个程序，实现了论文中的原结果了吗？
期望得到您的回复。
祝您生活愉快

**Comment by Cassieyy** [comment]
> 您好，我还有一个问题想请教您，您当初拿这个程序，实现了论文中的原结果了吗？ 期望得到您的回复。 祝您生活愉快

当时开源数据集下载出现问题，所以没有用开源数据集跑。

**Comment by lxy51** [comment]
1.那您当初拿你的数据跑通了吗？
2.效果如何？
